version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "9000"
        
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

volumes:
  wordpress:
    driver_opts:
      type: "local"
      o: bind
      device: /home/gmansuy/data/wordpress
  mariadb:
    driver_opts:
      type: "local"
      o: bind
      device: /home/gmansuy/data/mariadb

networks:
  inception:
    driver: bridge
