services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - my-net
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - my-net
    restart: unless-stopped
        
  db:
    container_name: db
    image: db
    build: ./requirements/mariadb/
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-net
    restart: unless-stopped

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: "local"
      o: bind
      device: /home/anaouadi/data/wordpress
  db:
    name: db
    driver_opts:
      type: "local"
      o: bind
      device: /home/anaouadi/data/db

networks:
  my-net:
    name: my-net
    driver: bridge
