CREATE DATABASE IF NOT EXISTS `wordpress`;
ALTER USER 'root'@localhost IDENTIFIED BY 'rootpass';
CREATE USER IF NOT EXISTS 'gmansuy'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'gmansuy'@'%' IDENTIFIED BY '123';
FLUSH PRIVILEGES;
